name       : python-tzlocal
version    : '2.1'
release    : 7
source     :
    - https://github.com/regebro/tzlocal/archive/refs/tags/2.1.tar.gz : 72ed8518bfa3506f7fed7f7205f468f70eaa4622b52c82d27fd9b8fb2d817631
homepage   : https://github.com/regebro/tzlocal
license    : MIT
component  : programming.python
summary    : A Python module that tries to figure out what your local timezone is
description: |
    This Python module returns a tzinfo object with the local timezone information. It attempts to fix a glaring hole in pytz, that there is no way to get the local timezone information, unless you know the zoneinfo name, and under several Linux distros that's hard or impossible to figure out.
builddeps  :
    - python-mock
    - python-pytest
    - python-pytz
rundeps    :
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v tests/tests.py -k 'not test_fail'
