name       : python-tzlocal
version    : 2.0.0
release    : 2
source     :
    - https://github.com/regebro/tzlocal/archive/2.0.0.tar.gz : b7d71186f016732f65ad5f0a3fce6f43682a91a57a212fd57b43293ebd8afb42
license    : MIT
component  : programming.python
summary    : A Python module that tries to figure out what your local timezone is
description: |
    This Python module returns a tzinfo object with the local timezone information. It attempts to fix a glaring hole in pytz, that there is no way to get the local timezone information, unless you know the zoneinfo name, and under several Linux distros that's hard or impossible to figure out.
builddeps  :
    - python-mock
    - python-pytz
rundeps    :
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install

    # Don't install the tests, duh!
    rm -fr $installdir/usr/lib/python3.6/site-packages/tzlocal/test*
    rm -fr $installdir/usr/lib/python3.6/site-packages/tzlocal/__pycache__/tests.*
check      : |
    %python3_test
